name: Release

on:
  release:
    types: [published]
    branches:
      - "main"

jobs:
  release:
    name: Release
    uses: molssi-seamm/devops/.github/workflows/Release.yaml@main
    with:
      src : seamm_datastore
      test_dir: seamm_datastore/tests
    secrets: inherit

